// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default Firebase configuration options for the current platform
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'Web platform is not supported yet - configure Firebase for web manually',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'iOS platform is not configured yet - add iOS configuration if needed',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'macOS is not supported for this app.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'Windows is not supported for this app.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'Linux is not supported for this app.',
        );
      default:
        throw UnsupportedError(
          'Unknown platform ${defaultTargetPlatform}',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdzyG8egHAoCVJ00OnmYy_le3qjHpLv7U',
    appId: '1:394459987236:android:061cdc2e4ac088d5f0c7b1',
    messagingSenderId: '394459987236',
    projectId: 'e7kky-c9fd2',
  );
}
