// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8Lkio2hhvDVDz5orl9XQYkplUC-HuM0I',
    appId: '1:897581906219:web:de3240e677abfa5c00ad6e',
    messagingSenderId: '897581906219',
    projectId: 'qcutapp-d6a09',
    authDomain: 'qcutapp-d6a09.firebaseapp.com',
    storageBucket: 'qcutapp-d6a09.firebasestorage.app',
    measurementId: 'G-DXTG4XKRVB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkGsH0hWkAEc4FrGKZtbl-Ycci5UMKEYA',
    appId: '1:897581906219:android:b11a53442ac6975200ad6e',
    messagingSenderId: '897581906219',
    projectId: 'qcutapp-d6a09',
    storageBucket: 'qcutapp-d6a09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFu3JSGV7LTc_1HoX-crm_SuXqicZXv_g',
    appId: '1:897581906219:ios:78aadf5fd4bb8e7100ad6e',
    messagingSenderId: '897581906219',
    projectId: 'qcutapp-d6a09',
    storageBucket: 'qcutapp-d6a09.firebasestorage.app',
    iosBundleId: 'com.example.qCut',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFu3JSGV7LTc_1HoX-crm_SuXqicZXv_g',
    appId: '1:897581906219:ios:78aadf5fd4bb8e7100ad6e',
    messagingSenderId: '897581906219',
    projectId: 'qcutapp-d6a09',
    storageBucket: 'qcutapp-d6a09.firebasestorage.app',
    iosBundleId: 'com.example.qCut',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8Lkio2hhvDVDz5orl9XQYkplUC-HuM0I',
    appId: '1:897581906219:web:ea154e8e0386764500ad6e',
    messagingSenderId: '897581906219',
    projectId: 'qcutapp-d6a09',
    authDomain: 'qcutapp-d6a09.firebaseapp.com',
    storageBucket: 'qcutapp-d6a09.firebasestorage.app',
    measurementId: 'G-YWV2537NFK',
  );
}
